version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: geopolitics_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: geopolitics_2025
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7
    container_name: geopolitics_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    container_name: geopolitics_backend
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://admin:admin@postgres:5432/geopolitics_2025
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.frontend
    container_name: geopolitics_frontend
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
